### ISSUE TITLE
Cloudflare R2 example

### ISSUE THREAD

**Issue by phpb-com** [Klowner/tussle#5]
https://github.com/Klowner/tussle/tree/main/examples/cloudflare-worker-r2 works for upload but how does one suppose to reassemble the file for reading/processing/downloading ? Despite Readme stating that files are available for download after uploading, I could not find any meaningful way to do it. Thanks.

**Comment by Klowner** [comment]
Good question, I need better documentation.

`TussleStorageR2` has a `getFile()` method which returns an `R2File` instance.

`R2File` has a `body` property which exposes a `ReadableStream` which handles reassembling the parts in correct order and returning them as a single stream.

If you have thousands of file parts, you will likely need to get a little more creative since you'll probably exhaust the Cloudflare Worker's CPU limits or R2 API call limits, in which case you can devise your own implementation by iterating over the `R2File`'s `keys` array (which is just an ordered array of R2 object keys representing the file parts).

**Comment by Klowner** [comment]
You could always add an after-complete handler that stores the R2File.body
as a new single R2 object and then delete the `keys`.
